# Generated by Django 3.1.3 on 2023-08-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230803_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='enrollement',
            new_name='enrollment',
        ),
    ]
